# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

# Podman stable (tracks the latest released Fedora) — tests unexpected
# env setups
FROM quay.io/podman/stable:latest

{% include "_header.j2" %}

RUN dnf install -y \
    dbus-daemon \
    gcc python3-devel dbus-devel glib2-devel pkgconf meson \
    python3 python3-pip \
    git curl \
    $EXTRA_PACKAGES \
    && dnf clean all

# The podman image ships a pre-existing 'podman' user (uid 1000).
WORKDIR /src
